[package]
name = "gst-video-host"
version = "0.1.0"
edition.workspace = true

[[bin]]
name = "livi-gst-host"
path = "src/main.rs"

[dependencies]
livi-audio-player = { path = "../audioplayer" }
livi-audio-stream = { path = "../audio" }
livi-audio-uplink = { path = "../mic" }
livi-host-proto = { path = "../../../livi-host-proto/rust" }
livi-screen-stream = { path = "../screen" }
livi-video-fanout = { path = "../fanout" }
livi-video-nal = { path = "../nal" }
livi-video-player = { path = "../player" }
realfft = "3.5.0"
glib = "0.21"
libc.workspace = true
