[package]
name = "livi-web"
version = "0.1.0"
edition.workspace = true

[lib]
name = "livi_web"
path = "src/lib.rs"

[dependencies]
livi-wifi = { path = "../../../livi-helperd/crates/livi-wifi" }
livi-wifid = { path = "../livi-wifid" }
livi-net = { path = "../../../livi-helperd/crates/livi-net" }
libc.workspace = true
